# Generated by Django 4.2 on 2025-09-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0002_alter_deported_iddescripciondeporte_delete_d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deported',
            name='horario',
            field=models.TimeField(verbose_name='horario'),
        ),
        migrations.AlterField(
            model_name='deported',
            name='iddescripciondeporte',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='descripciondeporte'),
        ),
    ]
