# Generated by Django 4.2 on 2025-09-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0003_alter_deported_horario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deported',
            name='iddescripciondeporte',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='iddescripciondeporte'),
        ),
    ]
