# Generated by Django 4.2 on 2025-10-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deportes', '0004_alter_deported_iddescripciondeporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deported',
            name='horario',
            field=models.TextField(verbose_name='horario'),
        ),
    ]
