# Generated by Django 4.2 on 2025-08-27 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organizador',
            fields=[
                ('idOrganizador', models.AutoField(db_column='idOrganizador', primary_key=True, serialize=False, verbose_name='idOrganizador')),
                ('nom', models.CharField(max_length=45, verbose_name='nombre')),
                ('contacto', models.IntegerField(verbose_name='contacto')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('idEvento', models.AutoField(db_column='idEvento', primary_key=True, serialize=False, verbose_name='idEvento')),
                ('nom', models.CharField(max_length=50, verbose_name='Nombre del Evento')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('fecha', models.DateTimeField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('ubicacion', models.CharField(max_length=100, verbose_name='Ubicación')),
                ('capacidad_max', models.PositiveIntegerField(blank=True, null=True, verbose_name='Capacidad Máxima')),
                ('tipo', models.CharField(choices=[('PEÑA', 'Peña'), ('FIESTA', 'Fiesta'), ('TORNEO', 'Torneo'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='ACTIVO', max_length=20)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Costo')),
                ('idOrganizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evento.organizador', verbose_name='Organizador')),
            ],
        ),
    ]
