# Generated by Django 4.2 on 2025-07-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizador',
            name='contacto',
            field=models.IntegerField(max_length=12, verbose_name='contacto'),
        ),
    ]
