# Generated by Django 4.2 on 2025-07-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_alter_organizador_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizador',
            name='contacto',
            field=models.IntegerField(max_length=25, verbose_name='contacto'),
        ),
    ]
