# Generated by Django 4.2 on 2025-08-19 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50, verbose_name='descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Talla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(max_length=50, verbose_name='talla')),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('DNI', models.IntegerField(verbose_name='DNI')),
                ('nom', models.CharField(max_length=50, verbose_name='Nombre y Apellido')),
                ('fechan', models.DateField(verbose_name='Fecha Nacimiento')),
                ('altura', models.FloatField(max_length=3, verbose_name='Altura')),
                ('peso', models.FloatField(max_length=3, verbose_name='Peso')),
                ('dire', models.CharField(max_length=50, verbose_name='Direccion')),
                ('cd', models.CharField(max_length=6, verbose_name='codigo postal')),
                ('qr', models.ImageField(blank=True, null=True, upload_to='jugadores/qr/', verbose_name='QR')),
                ('descripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jugadores.deporte', verbose_name='descripcion')),
                ('talla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jugadores.talla', verbose_name='talla')),
            ],
        ),
    ]
