# Generated by Django 4.2 on 2025-07-22 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='qr_data',
            field=models.FileField(blank=True, null=True, upload_to='jugadores/qr_data/', verbose_name='QR Datos'),
        ),
    ]
