# Generated by Django 4.2 on 2025-07-30 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jugadores', '0002_jugador_qr_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugador',
            name='qr_data',
        ),
    ]
