# Generated by Django 5.0.6 on 2025-10-02 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuota', '0001_initial'),
        ('jugadores', '0002_jugador_idcuota_jugador_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='enviado_whatsapp',
            field=models.BooleanField(default=False, verbose_name='Mensaje WhatsApp enviado'),
        ),
        migrations.AddField(
            model_name='jugador',
            name='idCuota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuota.cuota', verbose_name='idCuota'),
        ),
    ]
