# Generated by Django 5.0.6 on 2025-10-01 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuota', '0001_initial'),
        ('jugadores', '0003_remove_jugador_qr_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugador',
            name='idCuota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuota.cuota', verbose_name='idCuota'),
        ),
    ]
