# Generated by Django 4.2 on 2025-08-06 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to='socios/qr/', verbose_name='QR'),
        ),
    ]
