# Generated by Django 4.2 on 2025-08-11 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_socio_qr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='qr',
            field=models.ImageField(blank=True, null=True, upload_to='qrs/'),
        ),
    ]
