# Generated by Django 3.1 on 2025-06-13 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SociosCuota',
            fields=[
                ('idCuota', models.AutoField(db_column='idCuota', primary_key=True, serialize=False, verbose_name='idCuota')),
                ('nom', models.CharField(max_length=50, verbose_name='Nombre y Apellido')),
                ('cuotaMes', models.DateField(verbose_name='Cuota Mes')),
                ('fechap', models.DateField(verbose_name='Fecha de Pago')),
                ('importe', models.FloatField(max_length=10, verbose_name='importe')),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socios.socio', verbose_name='id')),
            ],
        ),
    ]
