# Generated by Django 5.0.6 on 2025-08-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('idServicio', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Contratacion',
            fields=[
                ('idContratacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('nomContratante', models.CharField(max_length=100)),
                ('servicios', models.ManyToManyField(related_name='contrataciones', to='servicios.servicio')),
            ],
        ),
    ]
