# Generated by Django 5.0.6 on 2025-08-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratacion',
            name='total_costo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='contratacion',
            name='servicios',
            field=models.ManyToManyField(to='servicios.servicio'),
        ),
    ]
