# Generated by Django 4.2 on 2025-08-12 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_alter_contratacion_nomcontratante'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratacion',
            name='servicios',
            field=models.ManyToManyField(related_name='contrataciones', to='servicios.servicio', verbose_name='Servicios'),
        ),
        migrations.AlterField(
            model_name='contratacion',
            name='idServicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrataciones_id', to='servicios.servicio', verbose_name='idServicio'),
        ),
    ]
